version: '3.8'

services:
  api:
    image: python:3.13-slim
    working_dir: /app
    command: sh -c "pip install uv && uv sync && uv run uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload --reload-exclude tests"
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
