version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=sentry
      - POSTGRES_PASSWORD=sentry_password
      - POSTGRES_DB=sentry
    volumes:
      - postgres-data:/var/lib/postgresql/data
  sentry:
    image: sentry:latest
    environment:
      - SENTRY_SECRET_KEY=your_secret_key
      - SENTRY_DB_USER=sentry
      - SENTRY_DB_PASSWORD=sentry_password
      - SENTRY_DB_NAME=sentry
      - SENTRY_DB_HOST=db
    depends_on:
      - postgres
    ports:
      - "9000:9000"
    volumes:
      - sentry-data:/data

volumes:
  postgres-data:
  sentry-data: